[package]
name = "num_field_quad"
version = "0.1.0"
authors = ["Matthew Torrence <matt@torrencefamily.net>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
num-traits = "0.2.12"
derive_more = "0.99.10"
alga = "0.9.3"
alga_derive = "0.9.2"
